version: '3'

services:
  employees-app:
    image: employees
    expose:
      - 8080

  employees-newman:
    build: .
    image: employees-newman
    volumes:
      - ./reports:/tests/reports
      - ./wait:/opt/wait
    depends_on:
      - employees-app
    entrypoint: ["/opt/wait/wait-for-it.sh", "-t", "30", "employees-app:8080", "--", "newman", "run", "employees.postman_collection.json", "-e", "test.postman_environment.json", "-r", "cli,htmlextra", "--reporter-htmlextra-export", "reports"]